---
title: 运维平台常见问题记录
date: 2019-04-17 17:57:42
categories: 
- 运维
tags: 
- Linux
---

##  192.168.9.101   

###  运维环境
    leap集群:LEAPV6    Tomcat04,Tomcat05   Geode:30001,30002,35001,35002
    
    项目集群：LCUCTEST  Tomcat06    Geode：30008,35008

1. 启动leap集群的时候，可以正常启动，但是Tomcat日志出现这个

![](https://raw.githubusercontent.com/supbadboy/image/master/20190410162256.png)

![](https://raw.githubusercontent.com/supbadboy/image/master/20190410162412.png)

```java

    警告: JGRP000012: discarded message from different cluster EXAMKS_LEAPCacheBus (our cluster is LEAPCacheBus_LCUCV6DEV). Sender was 9cbbd92f-8c2e-7157-3e62-b59c0e217491 (received 5 identical messages from 9cbbd92f-8c2e-7157-3e62-b59c0e217491 in the last 79924 ms)
[warn 2019/04/10 16:12:20.982 CST <Sync-phonebookUser> tid=0xbd] Pool unexpected socket timed out on client connection=Pooled Connection to 192.168.9.101:35001: Connection[192.168.9.101:35001]@1477556984 attempt=2)

[warn 2019/04/10 16:12:20.987 CST <Sync-phonebookUser> tid=0xbd] Pool unexpected socket timed out on client connection=Pooled Connection to 192.168.9.101:35001: Connection[192.168.9.101:35001]@1477556984 attempt=2). Server unreachable: could not connect after 2 attempts

[LEAPERROR] [16:12:20] LEAP - 查询缓存数据失败，region:leaporganization
[LEAPERROR] [16:12:20] LEAP - 	
	Type            :	org.apache.geode.cache.query.QueryInvocationTargetException
	Cause            :	org.apache.geode.cache.client.ServerConnectivityException: Pool unexpected socket timed out on client connection=Pooled Connection to 192.168.9.101:35001: Connection[192.168.9.101:35001]@1477556984 attempt=2). Server unreachable: could not connect after 2 attempts
	LocalizedMessage :	Pool unexpected socket timed out on client connection=Pooled Connection to 192.168.9.101:35001: Connection[192.168.9.101:35001]@1477556984 attempt=2). Server unreachable: could not connect after 2 attempts
	Message          :	Pool unexpected socket timed out on client connection=Pooled Connection to 192.168.9.101:35001: Connection[192.168.9.101:35001]@1477556984 attempt=2). Server unreachable: could not connect after 2 attempts
Cause StackTrace:		0  Class:org.apache.geode.cache.client.internal.OpExecutorImpl  Method:handleException  Line:790
		1  Class:org.apache.geode.cache.client.internal.OpExecutorImpl  Method:handleException  Line:631
		2  Class:org.apache.geode.cache.client.internal.OpExecutorImpl  Method:execute  Line:187
		3  Class:org.apache.geode.cache.client.internal.OpExecutorImpl  Method:execute  Line:128
		4  Class:org.apache.geode.cache.client.internal.PoolImpl  Method:execute  Line:758
		5  Class:org.apache.geode.cache.client.internal.QueryOp  Method:execute  Line:59
		6  Class:org.apache.geode.cache.client.internal.ServerProxy  Method:query  Line:69
		7  Class:org.apache.geode.internal.cache.LocalRegion  Method:query  Line:10650
		8  Class:com.longrise.LEAP.Base.Geode.Extend.GeodeBeanRegion  Method:search  Line:595
		9  Class:com.longrise.LEAP.Base.Geode.Extend.GeodeBeanRegion  Method:search  Line:845
		10  Class:com.longrise.LEAP.Base.Geode.Extend.GeodeBeanRegion  Method:search  Line:1
		11  Class:com.longrise.LEAP.Base.ServiceLayer.Logic.CacheSearch  Method:beanSearch  Line:143
		12  Class:com.longrise.LEAP.Base.ServiceLayer.Logic.CacheSearch  Method:beanSearch  Line:109
		13  Class:com.longrise.LEAP.Base.ServiceLayer.Logic.QueryService  Method:beanSearch  Line:25
		14  Class:com.longrise.Studiov2.User.UserLogic.UserSync  Method:studiov2_syncLeapuser  Line:94
		15  Class:com.longrise.Studiov2.AddressBook.SyncPhoneBookTimer  Method:run  Line:31
		16  Class:java.util.TimerThread  Method:mainLoop  Line:555
		17  Class:java.util.TimerThread  Method:run  Line:505StackTrace:		0  Class:org.apache.geode.internal.cache.LocalRegion  Method:query  Line:10656
		1  Class:com.longrise.LEAP.Base.Geode.Extend.GeodeBeanRegion  Method:search  Line:595
		2  Class:com.longrise.LEAP.Base.Geode.Extend.GeodeBeanRegion  Method:search  Line:845
		3  Class:com.longrise.LEAP.Base.Geode.Extend.GeodeBeanRegion  Method:search  Line:1
		4  Class:com.longrise.LEAP.Base.ServiceLayer.Logic.CacheSearch  Method:beanSearch  Line:143
		5  Class:com.longrise.LEAP.Base.ServiceLayer.Logic.CacheSearch  Method:beanSearch  Line:109
		6  Class:com.longrise.LEAP.Base.ServiceLayer.Logic.QueryService  Method:beanSearch  Line:25
		7  Class:com.longrise.Studiov2.User.UserLogic.UserSync  Method:studiov2_syncLeapuser  Line:94
		8  Class:com.longrise.Studiov2.AddressBook.SyncPhoneBookTimer  Method:run  Line:31
		9  Class:java.util.TimerThread  Method:mainLoop  Line:555
		10  Class:java.util.TimerThread  Method:run  Line:505
```

2. 尝试重启leap集群geode和项目集群geode，全部启动时间17:15，开始启动项目集群，开始出现问题，又开始重新put数据

![](https://raw.githubusercontent.com/supbadboy/image/master/20190410172009.png)



3. 运维平台的日志  leaperrer.log

![](https://raw.githubusercontent.com/supbadboy/image/master/20190410173712.png)


4. 数据库出现数据混乱的问题 

![](https://raw.githubusercontent.com/supbadboy/image/master/20190411150657.png)

问题出在city表和country表，数据成倍的增多，出现很多id长度为1-4，
在数据中删除id不对的数据
```
select count(*) from community
union all
select count(*) from province
union all
select count(*) from city
union all
select count(*) from county
union all
select count(*) from street
	//数据对比

select l_strlen(id), * from county order by provinceid, cityid desc
select l_strlen(id), * from city order by provinceid, cityid desc

select count(*) from city where l_strlen(id) < 32

— delete from city where l_strlen(id) < 30
	//删除id长度不对的数据
```

5. 9.101的  换上了0409的基础包  用的是1.6的geode  leap集群使用的是新的空的数据库  开发机器也是新的geode  之前备份的数据库
然后现在出现的是

![](https://raw.githubusercontent.com/supbadboy/image/master/20190411163324.png)

登录进去没有数据  开发机器日志上暂时没有报错   尝试更换  base基础包



6. leap集群的geode日志显示

![](https://raw.githubusercontent.com/supbadboy/image/master/20190411164715.png)

开发机器 geode 日志显示

![](https://raw.githubusercontent.com/supbadboy/image/master/20190411164855.png)

7. 服务器启动的端口数量

	![](https://raw.githubusercontent.com/supbadboy/image/master/20190412102553.png)

8. NVIS项目启动，发现错误日志，但是好像并没有影响到开发机器的正常运行

![](https://raw.githubusercontent.com/supbadboy/image/master/20190412110552.png)

![](https://raw.githubusercontent.com/supbadboy/image/master/20190412110857.png)

![](https://raw.githubusercontent.com/supbadboy/image/master/20190412111118.png)


##  2019-04-12 日志

####  开发机全部更换lib的 LEAP.Studio.Bll.jar包  

1. 大概十分钟后Tomcat重复出现get的日志，本地开发机器一个项目，三台机器。

![](https://raw.githubusercontent.com/supbadboy/image/master/20190412144937.png)

2. 开发机挂了之后，重新启动的时候，始终停留在这个界面

![](https://raw.githubusercontent.com/supbadboy/image/master/20190412145340.png)

3. 在开发机器挂掉的情况下，如果开发机器重新，leap集群的geode会出现这个日志

![](https://raw.githubusercontent.com/supbadboy/image/master/20190412150043.png)

![](https://raw.githubusercontent.com/supbadboy/image/master/20190412170909.png)

4. 项目集群的geode同步的日志跟leap集群geode的日志相同 

![](https://raw.githubusercontent.com/supbadboy/image/master/20190412150043.png)

####  leap集群也更换lib的  LEAP.Studio.BLL.jar包，暂时只重启leap集群Tomcat

5. 更换新的包之后  在leaperror.log里面看到的错误信息

![](https://raw.githubusercontent.com/supbadboy/image/master/20190412183018.png)



## 20190416 在101运维平台开始部署测试leap集群，分别部署到两个运维平台

### geode创建成功，member成员显示成员都存在，但是状态是灰色的

![](https://raw.githubusercontent.com/supbadboy/image/master/20190416110922.png)

### 首次启动Tomcat的时候，遇到从未看到的日志

![](https://raw.githubusercontent.com/supbadboy/image/master/20190416110438.png)


### 前端方法调用过度导致内存不足
![](https://raw.githubusercontent.com/supbadboy/image/master/20190416142143.png)


### 0423 项目集群运行的时候出现这个错误
![](https://raw.githubusercontent.com/supbadboy/image/master/20190423174034.png)

- 这种情况可能是geode的servser出现错误，尝试重启geode
- 更换leap集群的基础包

![](https://raw.githubusercontent.com/supbadboy/image/master/20190423174216.png)

- 删除geode重现创建新的geode


### 0425 运维平台开始变的卡顿，点服务清单和系统清单卡顿，安装geode超时，显示失败

![](https://raw.githubusercontent.com/supbadboy/image/master/20190426092357.png)

在geode清单上显示geode的状态都是没问题，这个时候会出现两种情况，

一种是geode安装成功，后台服务可以正常启动

一种是geode安装失败，本地开发机器运行的时候会出现两种错误

![](https://raw.githubusercontent.com/supbadboy/image/master/20190423174216.png)

![](https://raw.githubusercontent.com/supbadboy/image/master/20190426092348.png)

+ 问题还在解决中...